### ISSUE TITLE
Microsecond timer

### ISSUE THREAD

**Issue by hasmqtt** [rsegecin/ESP8266Timer#1]
Hi,

I do not see any function which can support microsecond timer, is it possible to enhance this library to support microsecond timer ?

Thanks

**Comment by rsegecin** [comment]
Yes you can but I don't think it'll cope really well depending on your application. As you know ESP8266's micro-controller just have a "single thread" and it has to attend interrupts that might take more than a microsecond to process but just might as well give it a go (interrupt routines should be kept to a minimum anyway). To do it the method `TimeCounterClass::timerCallback()` is called every microsecond already so you'll just have to add a microsecond variable to sTimeSpan and every where it should apply. Note that I haven't tested at microsecond level pulse with a osciloscope so it should be checked as well.

**Comment by hasmqtt** [comment]
Thanks for quick response, in that case may be I will try adding another micro controller like pic to support microsecond timer.
